FROM ubuntu:22.04
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip \
    libpq-dev \
    libldap2-dev \
    libsasl2-dev \
    && rm -rf /var/lib/apt/lists/*

# Installar el postgres cliente en el odoo
RUN apt-get update && apt-get install -y postgresql-client

#Anañdir el usuario odoo, no admin role para seguridad 
RUN useradd -ms /bin/bash odoo

# git clone el repositorio de odoo
RUN git clone --depth=1 https://github.com/odoo/odoo.git /odoo

WORKDIR /odoo

#instalar los dependencias
RUN pip3 install -r requirements.txt

COPY odoo_init.sh /odoo/odoo_init.sh
COPY odoo.conf /odoo/odoo.conf
RUN chmod +x /odoo/odoo_init.sh

USER odoo

# Ejecutar el servicio odoo
CMD ["/odoo/odoo_init.sh"]
